#!/usr/bin/env python3
"""Regenerate INDEX.md from sites/. Run after any change; CI checks it is current."""
from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parents[1]
rows = []
for f in sorted((ROOT / "sites").glob("*.yaml")):
    s = yaml.safe_load(f.read_text())
    sid = s["host"] + s.get("path_scope", "")
    conf = [t["attribution"]["confidence"] for t in s["traces"]]
    best = next((c for c in ["confirmed", "likely", "possible", "unattributed"] if c in conf), "—")
    rows.append((
        f"[{sid}](sites/{f.name})",
        s["platform"]["kind"],
        ", ".join(s.get("campaigns") or ["—"]),
        str(s.get("first_seen", "")) or "—",
        str(s.get("last_seen", "")) or "—",
        str(len(s["traces"])),
        best,
        s["status"]["state"],
    ))

hdr = ["site", "kind", "campaign", "first seen", "last seen", "traces", "best attribution", "state"]
out = ["# Index", "", "Generated by `scripts/build_index.py` — do not edit.", "",
       "| " + " | ".join(hdr) + " |", "|" + "---|" * len(hdr)]
out += ["| " + " | ".join(r) + " |" for r in rows]
out += ["", f"{len(rows)} sites · {sum(int(r[5]) for r in rows)} traces"]
(ROOT / "INDEX.md").write_text("\n".join(out) + "\n")
print(f"INDEX.md: {len(rows)} sites")
